# Generated by Django 4.2.20 on 2025-04-08 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Workshop',
        ),
    ]
