# Generated by Django 4.2.20 on 2025-04-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='resonse',
            field=models.TextField(null=True),
        ),
    ]
