# Generated by Django 4.2.20 on 2025-04-14 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_resonse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='resonse',
            new_name='response',
        ),
    ]
