# Generated by Django 4.2.20 on 2025-04-14 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_workshop_owner'),
        ('bookings', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='workshops.service'),
        ),
    ]
